version: '3.8'

services:
  db:
    image: ghcr.io/smh12355/projectmanagerdb:latest
    container_name: database
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123   
      MYSQL_USER: smh                   
      MYSQL_PASSWORD: 12355           
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectmanager_app
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=db;User=smh;Password=12355;CharSet=utf8mb4;
    ports:
      - "8080:80"
      
volumes:
  db_data:
