version: '3.8'

services:
  db:
    image: ${DOCKER_REGISTRY}
    container_name: my_sql_database
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123   
      MYSQL_USER: smh                   
      MYSQL_PASSWORD: 12355           
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: PM_BACKEND
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=my_sql_database;Database=db;User=smh;Password=12355;CharSet=utf8mb4;
    ports:
      - "8080:80"
      
volumes:
  db_data:
