version: '3.8'

services:
  db:
    image: ${DOCKER_REGISTRY}
    container_name: my_sql_database
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 123   
      MYSQL_USER: smh                   
      MYSQL_PASSWORD: 12355           
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
