// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManager.Infrastructure;

#nullable disable

namespace ProjectManager.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectManagerDbContext))]
    [Migration("20240528103346_push_data_to_db")]
    partial class push_data_to_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.DesignObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentDesignObjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDesignObjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("DesignObjects");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.DocSetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DesignObjectId")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesignObjectId");

                    b.ToTable("DocSets");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.DesignObjectEntity", b =>
                {
                    b.HasOne("ProjectManager.Infrastructure.Entities.DesignObjectEntity", "ParentDesignObject")
                        .WithMany("ChildrenDesignObjects")
                        .HasForeignKey("ParentDesignObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManager.Infrastructure.Entities.ProjectEntity", "Project")
                        .WithMany("DesignObjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDesignObject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.DocSetEntity", b =>
                {
                    b.HasOne("ProjectManager.Infrastructure.Entities.DesignObjectEntity", "DesignObject")
                        .WithMany("DocSets")
                        .HasForeignKey("DesignObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignObject");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.DesignObjectEntity", b =>
                {
                    b.Navigation("ChildrenDesignObjects");

                    b.Navigation("DocSets");
                });

            modelBuilder.Entity("ProjectManager.Infrastructure.Entities.ProjectEntity", b =>
                {
                    b.Navigation("DesignObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
